DATA_PATH: "/data/mciacco/KXiCorrelations"
MC_SIGNAL_PATH: "/data/mciacco/KXiCorrelations/AnalysisResults_0_90.root"

CT_BINS: [[0,1],[1,2],[2,3],[3,4],[4,5],[5,10]] # training
CT_BINS_CENT:  [[0,1,2,3,4,5,10]] #,[0,1,2,3,4,5,10],[0,1,2,3,4,5,10],[0,1,2,3,4,5,10],[0,1,2,3,4,5,10],[0,1,2,3,4,5,10],[0,1,2,3,4,5,10],[0,1,2,3,4,5,10],[0,1,2,3,4,5,10]]
PT_BINS: [[1.,1.5],[1.5,2],[2,2.5],[2.5,3],[3,4]]
PT_BINS_CENT: [[1.,1.5,2,2.5,3,4]] #,[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4],[1.,1.5,2,2.5,3,4]]
#CENTRALITY_LIST:  [[0,10],[10,20],[20,30],[30,40],[40,50],[50,60],[60,70],[70,80],[80,90]] #[[0,90]]
#CENTRALITY_BINS:  [0,10,20,30,40,50,60,70,80,90] #[[0,90]]
CENTRALITY_LIST:  [[0,90]]
CENTRALITY_BINS:  [0,90]

RANDOM_STATE: 42

HYPERPARAMS:
  n_estimators: 300
  max_depth: 3
  learning_rate: 0.05
  gamma: 1
  # learning_rate: 0.0982
  # n_estimators: 181
  seed: 42

HYPERPARAMS_RANGES:
  # booster parameters
  n_estimators: !!python/tuple [100,2000]
  max_depth: !!python/tuple [2,10]
  learning_rate: !!python/tuple [0.05,1.]
  gamma: !!python/tuple [0.2, 10.]
  subsample: !!python/tuple [0.5, 0.9]
  colsample_bytree: !!python/tuple [0.5, 0.9]
  # learning_rate: !!python/tuple [0.01, 0.3] # learning rate
  # n_estimators: !!python/tuple [50, 500] # number of boosting trees
  # gamma: !!python/tuple [0.3, 1.1] # specifies the minimum loss reduction required to make a split
  # min_child_weight: !!python/tuple [1, 12]
  # subsample: !!python/tuple [0.5, 0.9] # denotes the fraction of observations to be randomly samples for each tree
  # colsample_bytree: !!python/tuple [0.5, 0.9] # denotes the fraction of columns to be randomly samples for each tree

TRAINING_COLUMNS:
  #- radius #[0,25.4,8]
  #- radiusV0 #[0,25.4,8]
  - dcaBachPV #[0,2.54,8]
  - dcaV0PV #[0,2.54,16]
  - dcaV0piPV #[0,2.54,8]
  - dcaV0prPV #[0,2.54,8]
  - dcaV0tracks #[0,2.54,8]
  - dcaBachV0 #[0,2.54,8]
  - cosPA #[0.95,1,16]
  - cosPAV0 #[0.95,1,16]
  #- V0invMassDelta #[-0.01,0.01,8]
  #- tpcNsigmaBach #[-5,5,8]
  - tpcNsigmaV0Pr #[-5,5,8]
  #- tpcNsigmaV0Pi #[-5,5,8]
  #- competingMass #[0,0.254,8]
  #- bachBarCosPA #[0.9999, 1., 8]
  #- tpcClBach
  #- tpcClV0Pr
  #- tpcClV0Pi